# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/data-science-blog',
                'doc_host': 'https://tugot17.github.io',
                'git_url': 'https://github.com/tugot17/data-science-blog',
                'lib_path': 'data_science_blog'},
  'syms': {'data_science_blog.core': {'data_science_blog.core.foo': ('core.html#foo', 'data_science_blog/core.py')}}}
